### ISSUE TITLE
运行后提示找不到网络名

### ISSUE THREAD

**Issue by J-Deep** [HaujetZhao/Protect-Windows-Context-Menu#2]
PsExec v2.4 - Execute processes remotely
Copyright (C) 2001-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

Error creating key file on DESKTOP-OHJ2HUG:
找不到网络名。

**Comment by HaujetZhao** [comment]
是运行01脚本吗？





------------------ 原始邮件 ------------------
发件人: jascry ***@***.***&gt;
发送时间: 2023年4月25日 12:41
收件人: HaujetZhao/Protect-Windows-Context-Menu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [HaujetZhao/Protect-Windows-Context-Menu] 运行后提示找不到网络名 (Issue #2)





 
PsExec v2.4 - Execute processes remotely
 Copyright (C) 2001-2022 Mark Russinovich
 Sysinternals - www.sysinternals.com
 
Error creating key file on DESKTOP-OHJ2HUG:
 找不到网络名。

**Comment by J-Deep** [comment]
01和02运行后都是这样

**Comment by HaujetZhao** [comment]
晚上解决





------------------ 原始邮件 ------------------
发件人: jascry ***@***.***&gt;
发送时间: 2023年4月25日 12:55
收件人: HaujetZhao/Protect-Windows-Context-Menu ***@***.***&gt;
抄送: Haujet Zhao ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [HaujetZhao/Protect-Windows-Context-Menu] 运行后提示找不到网络名 (Issue #2)





 
01和02运行后都是这样

**Comment by HaujetZhao** [comment]
我在 Win7 和 Win10 虚拟机上，都没有复现这个情况。加 qq 联系下吧 1292756898，提前下载上 ToDesk，我远程看下是什么问题。

**Comment by HaujetZhao** [comment]
## 问题原因

缺失 [administrative shares](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/problems-administrative-shares-missing) ，具体原因不明，可能是恶意软件关了，也可能是杀软关了（我更倾向于这种情况），这导致 psexec 无法以 system 权限执行命令。

管理员权限运行 `net share` 命令，正常可以看到有 `admin$` 项：

```
共享名       资源                            注解

-------------------------------------------------------------------------------
ADMIN$       C:\Windows                      远程管理
```

当 administrative shares 被关掉时，就看不到 `admin$` 了。

## 解决办法

再手动打开 administrative shares 。以管理员权限运行 cmd，在里面执行这两条命令：

```
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" /v "AutoShareServer" /t REG_DWORD /d 1 /f

reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" /v "AutoShareWks" /t REG_DWORD /d 1 /f
```

然后重启电脑即可解决。
