### ISSUE TITLE
遇到错误，exited with error code 0有解决办法吗

### ISSUE THREAD

**Issue by Huangbinghui** [HaujetZhao/Protect-Windows-Context-Menu#3]
PsExec v2.4 - Execute processes remotely
Copyright (C) 2001-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

cmd exited on DESKTOP-S1N67RN with error code 0.

**Comment by HaujetZhao** [comment]
error code 0 就是正常结束的意思。
